language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
env:
    - ARCH="i686"
    - ARCH="x86_64"
matrix:
  exclude:
    - os: osx
      env: ARCH="i686"
notifications:
  email: false
sudo: false
